### ISSUE TITLE
'Attenuation Plugin Settings' is missing

### ISSUE THREAD

**Issue by ghost** [resonance-audio/resonance-audio-unreal-sdk#4]
Absolutely the same issue: https://answers.unrealengine.com/questions/772757/google-resonance-cant-find-attenuation-plugin-sett.html

The section is missing. Everything else is done in accordance with documentation here: https://developers.google.com/resonance-audio/develop/unreal/getting-started

Please update your documentation or fix the issue. Thanks.

**Comment by mgorzel** [comment]
From the conversation in https://answers.unrealengine.com/questions/772757/google-resonance-cant-find-attenuation-plugin-sett.html, it sounds like the issue has been resolved (the issue was wrong UE4 version used). Closing.
